declare module '#og-image/components' {
  export interface OgImageComponents {
    'BlogPostSatori': typeof import('../../app/components/OgImage/BlogPost.satori.vue')['default']
    'BlogPost.satori': typeof import('../../app/components/OgImage/BlogPost.satori.vue')['default']
    'ImageBlogPost.satori': typeof import('../../app/components/OgImage/BlogPost.satori.vue')['default']
    'ImageBlogPost': typeof import('../../app/components/OgImage/BlogPost.satori.vue')['default']
    'BlogPostTakumi': typeof import('../../node_modules/nuxt-og-image/dist/runtime/app/components/Templates/Community/BlogPost.takumi.vue')['default']
    'BlogPost.takumi': typeof import('../../node_modules/nuxt-og-image/dist/runtime/app/components/Templates/Community/BlogPost.takumi.vue')['default']
    'BrutalistSatori': typeof import('../../node_modules/nuxt-og-image/dist/runtime/app/components/Templates/Community/Brutalist.satori.vue')['default']
    'Brutalist.satori': typeof import('../../node_modules/nuxt-og-image/dist/runtime/app/components/Templates/Community/Brutalist.satori.vue')['default']
    'Brutalist': typeof import('../../node_modules/nuxt-og-image/dist/runtime/app/components/Templates/Community/Brutalist.satori.vue')['default']
    'DocsTakumi': typeof import('../../node_modules/nuxt-og-image/dist/runtime/app/components/Templates/Community/Docs.takumi.vue')['default']
    'Docs.takumi': typeof import('../../node_modules/nuxt-og-image/dist/runtime/app/components/Templates/Community/Docs.takumi.vue')['default']
    'Docs': typeof import('../../node_modules/nuxt-og-image/dist/runtime/app/components/Templates/Community/Docs.takumi.vue')['default']
    'FrameSatori': typeof import('../../node_modules/nuxt-og-image/dist/runtime/app/components/Templates/Community/Frame.satori.vue')['default']
    'Frame.satori': typeof import('../../node_modules/nuxt-og-image/dist/runtime/app/components/Templates/Community/Frame.satori.vue')['default']
    'Frame': typeof import('../../node_modules/nuxt-og-image/dist/runtime/app/components/Templates/Community/Frame.satori.vue')['default']
    'NuxtSatori': typeof import('../../node_modules/nuxt-og-image/dist/runtime/app/components/Templates/Community/Nuxt.satori.vue')['default']
    'Nuxt.satori': typeof import('../../node_modules/nuxt-og-image/dist/runtime/app/components/Templates/Community/Nuxt.satori.vue')['default']
    'Nuxt': typeof import('../../node_modules/nuxt-og-image/dist/runtime/app/components/Templates/Community/Nuxt.satori.vue')['default']
    'NuxtSeoSatori': typeof import('../../node_modules/nuxt-og-image/dist/runtime/app/components/Templates/Community/NuxtSeo.satori.vue')['default']
    'NuxtSeo.satori': typeof import('../../node_modules/nuxt-og-image/dist/runtime/app/components/Templates/Community/NuxtSeo.satori.vue')['default']
    'NuxtSeoTakumi': typeof import('../../node_modules/nuxt-og-image/dist/runtime/app/components/Templates/Community/NuxtSeo.takumi.vue')['default']
    'NuxtSeo.takumi': typeof import('../../node_modules/nuxt-og-image/dist/runtime/app/components/Templates/Community/NuxtSeo.takumi.vue')['default']
    'PergelSatori': typeof import('../../node_modules/nuxt-og-image/dist/runtime/app/components/Templates/Community/Pergel.satori.vue')['default']
    'Pergel.satori': typeof import('../../node_modules/nuxt-og-image/dist/runtime/app/components/Templates/Community/Pergel.satori.vue')['default']
    'Pergel': typeof import('../../node_modules/nuxt-og-image/dist/runtime/app/components/Templates/Community/Pergel.satori.vue')['default']
    'ProductCardTakumi': typeof import('../../node_modules/nuxt-og-image/dist/runtime/app/components/Templates/Community/ProductCard.takumi.vue')['default']
    'ProductCard.takumi': typeof import('../../node_modules/nuxt-og-image/dist/runtime/app/components/Templates/Community/ProductCard.takumi.vue')['default']
    'ProductCard': typeof import('../../node_modules/nuxt-og-image/dist/runtime/app/components/Templates/Community/ProductCard.takumi.vue')['default']
    'SaaSSatori': typeof import('../../node_modules/nuxt-og-image/dist/runtime/app/components/Templates/Community/SaaS.satori.vue')['default']
    'SaaS.satori': typeof import('../../node_modules/nuxt-og-image/dist/runtime/app/components/Templates/Community/SaaS.satori.vue')['default']
    'SaaS': typeof import('../../node_modules/nuxt-og-image/dist/runtime/app/components/Templates/Community/SaaS.satori.vue')['default']
    'SimpleBlogSatori': typeof import('../../node_modules/nuxt-og-image/dist/runtime/app/components/Templates/Community/SimpleBlog.satori.vue')['default']
    'SimpleBlog.satori': typeof import('../../node_modules/nuxt-og-image/dist/runtime/app/components/Templates/Community/SimpleBlog.satori.vue')['default']
    'SimpleBlog': typeof import('../../node_modules/nuxt-og-image/dist/runtime/app/components/Templates/Community/SimpleBlog.satori.vue')['default']
    'UnJsSatori': typeof import('../../node_modules/nuxt-og-image/dist/runtime/app/components/Templates/Community/UnJs.satori.vue')['default']
    'UnJs.satori': typeof import('../../node_modules/nuxt-og-image/dist/runtime/app/components/Templates/Community/UnJs.satori.vue')['default']
    'UnJs': typeof import('../../node_modules/nuxt-og-image/dist/runtime/app/components/Templates/Community/UnJs.satori.vue')['default']
    'WithEmojiSatori': typeof import('../../node_modules/nuxt-og-image/dist/runtime/app/components/Templates/Community/WithEmoji.satori.vue')['default']
    'WithEmoji.satori': typeof import('../../node_modules/nuxt-og-image/dist/runtime/app/components/Templates/Community/WithEmoji.satori.vue')['default']
    'WithEmoji': typeof import('../../node_modules/nuxt-og-image/dist/runtime/app/components/Templates/Community/WithEmoji.satori.vue')['default']
  }
}
