import type { PageCollectionItemBase, DataCollectionItemBase } from '@nuxt/content'

declare module '@nuxt/content' {
   /* eslint-disable */
  /**
   * This file was automatically generated by json-schema-to-typescript.
   * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
   * and run json-schema-to-typescript to regenerate this file.
   */
  
  interface BlogCollectionItem extends PageCollectionItemBase {
    title: string;
    description: string;
    date: string;
    author?: string;
    categories?: string[];
    thumbnail?: string;
    hidden?: boolean;
  }
  

  interface PageCollections {
    blog: BlogCollectionItem
  }

  interface Collections {
    blog: BlogCollectionItem
  }
}
